/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BIT,
    weight_kg DECIMAL(18,2)
);
